version: '3.9'
services:
  db:
    container_name: postgres_container
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: ${username}
      POSTGRES_PASSWORD: ${password}
      POSTGRES_DB: ${schemas}
    ports:
      - "5432:5432"
    networks:
      - authentication-network
  authentication-with-jwt-spring-security:
    container_name: authentication-with-jwt-spring-security
    image: fricarte/authentication-with-jwt-spring-security
    restart: always
    build: ./
    working_dir: /authentication-with-jwt-spring-security
    environment:
      SPRING.DATASOURCE.URL: ${urldocker}
      SPRING.DATASOURCE.USERNAME: ${username}
      SPRING.DATASOURCE.PASSWORD: ${password}
    ports:
      - 8080:8080
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - authentication-network
networks:
  authentication-network:
    driver: bridge