security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  flyway:
    schemas: ${schemas}

  datasource:
    url: ${url}
    username: ${username}
    password: ${password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show-sql: true
        format-sql: true
    open-in-view: false

logging:
  level:
    org:
      springframework:
        web: INFO
        hibernate: INFO
